title: Masetra Documentation
description: "Comprehensive documentation for Masetra Quality Management System"
theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge

# GitHub Pages settings
baseurl: "/masetra-docs"
url: "https://masetra-group.github.io/masetra-docs/"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /docs/getting-started/installation
  - title: User Guide
    url: /docs/user-guide/deviations
  - title: Technical
    url: /docs/technical/architecture
  - title: Compliance
    url: /docs/compliance/regulatory

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed